/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  sym_number_literal = 6,
  sym_string_literal = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_regex_literal = 10,
  sym_plus = 11,
  sym_minus = 12,
  sym_bang = 13,
  sym_ternary_question = 14,
  sym_ternary_colon = 15,
  sym_and = 16,
  sym_or = 17,
  sym_string_concat = 18,
  sym_member_access = 19,
  sym_eq = 20,
  sym_ne = 21,
  sym_regex_eq = 22,
  sym_lt = 23,
  sym_lte = 24,
  sym_gt = 25,
  sym_gte = 26,
  sym_mul = 27,
  sym_div = 28,
  sym_modulo = 29,
  sym_mel = 30,
  sym_argument_list = 31,
  sym__arguments = 32,
  sym_argument = 33,
  sym_expr = 34,
  sym__hidden_expr = 35,
  sym__grouped_expr = 36,
  sym__simple_expr = 37,
  sym_assignment_expr = 38,
  sym_function_call_expr = 39,
  sym_binary_expr = 40,
  sym_prefix_expr = 41,
  sym__variable = 42,
  sym_member_access_expr = 43,
  sym_ternary_expr = 44,
  sym__literal_expr = 45,
  sym_literal = 46,
  sym_boolean_literal = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_regex_literal] = "regex_literal",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_bang] = "bang",
  [sym_ternary_question] = "ternary_question",
  [sym_ternary_colon] = "ternary_colon",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_string_concat] = "string_concat",
  [sym_member_access] = "member_access",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_regex_eq] = "regex_eq",
  [sym_lt] = "lt",
  [sym_lte] = "lte",
  [sym_gt] = "gt",
  [sym_gte] = "gte",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_modulo] = "modulo",
  [sym_mel] = "mel",
  [sym_argument_list] = "argument_list",
  [sym__arguments] = "_arguments",
  [sym_argument] = "argument",
  [sym_expr] = "expr",
  [sym__hidden_expr] = "_hidden_expr",
  [sym__grouped_expr] = "_grouped_expr",
  [sym__simple_expr] = "_simple_expr",
  [sym_assignment_expr] = "assignment_expr",
  [sym_function_call_expr] = "function_call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_prefix_expr] = "prefix_expr",
  [sym__variable] = "_variable",
  [sym_member_access_expr] = "member_access_expr",
  [sym_ternary_expr] = "ternary_expr",
  [sym__literal_expr] = "_literal_expr",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_regex_literal] = sym_regex_literal,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_bang] = sym_bang,
  [sym_ternary_question] = sym_ternary_question,
  [sym_ternary_colon] = sym_ternary_colon,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_string_concat] = sym_string_concat,
  [sym_member_access] = sym_member_access,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_regex_eq] = sym_regex_eq,
  [sym_lt] = sym_lt,
  [sym_lte] = sym_lte,
  [sym_gt] = sym_gt,
  [sym_gte] = sym_gte,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_modulo] = sym_modulo,
  [sym_mel] = sym_mel,
  [sym_argument_list] = sym_argument_list,
  [sym__arguments] = sym__arguments,
  [sym_argument] = sym_argument,
  [sym_expr] = sym_expr,
  [sym__hidden_expr] = sym__hidden_expr,
  [sym__grouped_expr] = sym__grouped_expr,
  [sym__simple_expr] = sym__simple_expr,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_function_call_expr] = sym_function_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_prefix_expr] = sym_prefix_expr,
  [sym__variable] = sym__variable,
  [sym_member_access_expr] = sym_member_access_expr,
  [sym_ternary_expr] = sym_ternary_expr,
  [sym__literal_expr] = sym__literal_expr,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_regex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_question] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_string_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_mel] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__hidden_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__grouped_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__variable] = {
    .visible = false,
    .named = true,
  },
  [sym_member_access_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__literal_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '!', 44,
        '"', 2,
        '%', 60,
        '(', 22,
        ')', 23,
        '*', 58,
        '+', 41,
        ',', 24,
        '-', 42,
        '.', 49,
        '/', 59,
        ':', 46,
        '<', 54,
        '=', 25,
        '>', 56,
        '?', 45,
        '^', 50,
        'a', 14,
        'f', 9,
        'o', 15,
        't', 16,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 't') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(47);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 19:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '!', 7,
        '%', 60,
        '(', 22,
        ')', 23,
        '*', 58,
        '+', 41,
        ',', 24,
        '-', 42,
        '.', 49,
        '/', 59,
        ':', 46,
        '<', 54,
        '=', 25,
        '>', 56,
        '?', 45,
        '^', 50,
        'a', 14,
        'o', 15,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_regex_literal);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_bang);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ternary_question);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ternary_colon);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string_concat);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_member_access);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_regex_eq);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_modulo);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 20},
  [16] = {.lex_state = 20},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 20},
  [28] = {.lex_state = 20},
  [29] = {.lex_state = 20},
  [30] = {.lex_state = 20},
  [31] = {.lex_state = 20},
  [32] = {.lex_state = 20},
  [33] = {.lex_state = 20},
  [34] = {.lex_state = 20},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 19},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_regex_literal] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_ternary_question] = ACTIONS(1),
    [sym_ternary_colon] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_string_concat] = ACTIONS(1),
    [sym_member_access] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_regex_eq] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_modulo] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_mel] = STATE(39),
    [sym_expr] = STATE(32),
    [sym__hidden_expr] = STATE(16),
    [sym__grouped_expr] = STATE(16),
    [sym__simple_expr] = STATE(16),
    [sym_assignment_expr] = STATE(16),
    [sym_function_call_expr] = STATE(16),
    [sym_binary_expr] = STATE(16),
    [sym_prefix_expr] = STATE(16),
    [sym__variable] = STATE(3),
    [sym_member_access_expr] = STATE(3),
    [sym_ternary_expr] = STATE(16),
    [sym__literal_expr] = STATE(16),
    [sym_literal] = STATE(16),
    [sym_boolean_literal] = STATE(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_regex_literal] = ACTIONS(7),
    [sym_bang] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__arguments] = STATE(36),
    [sym_argument] = STATE(36),
    [sym_expr] = STATE(34),
    [sym__hidden_expr] = STATE(30),
    [sym__grouped_expr] = STATE(30),
    [sym__simple_expr] = STATE(30),
    [sym_assignment_expr] = STATE(30),
    [sym_function_call_expr] = STATE(30),
    [sym_binary_expr] = STATE(30),
    [sym_prefix_expr] = STATE(30),
    [sym__variable] = STATE(3),
    [sym_member_access_expr] = STATE(3),
    [sym_ternary_expr] = STATE(30),
    [sym__literal_expr] = STATE(30),
    [sym_literal] = STATE(30),
    [sym_boolean_literal] = STATE(17),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(13),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_regex_literal] = ACTIONS(7),
    [sym_bang] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      sym_member_access,
    STATE(19), 1,
      sym_argument_list,
    ACTIONS(23), 2,
      sym_lt,
      sym_gt,
    ACTIONS(15), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [37] = 2,
    ACTIONS(27), 3,
      anon_sym_EQ,
      sym_lt,
      sym_gt,
    ACTIONS(25), 20,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_member_access,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [65] = 10,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(34), 1,
      sym_expr,
    STATE(37), 1,
      sym_argument,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(30), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [109] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(29), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [150] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(18), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [191] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(34), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(31), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [232] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(20), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [273] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(33), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [314] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(21), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [355] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(22), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [396] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(23), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [437] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(24), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym__variable,
      sym_member_access_expr,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(16), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [478] = 2,
    ACTIONS(31), 2,
      sym_lt,
      sym_gt,
    ACTIONS(29), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [503] = 2,
    ACTIONS(35), 2,
      sym_lt,
      sym_gt,
    ACTIONS(33), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [528] = 2,
    ACTIONS(39), 2,
      sym_lt,
      sym_gt,
    ACTIONS(37), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [553] = 2,
    ACTIONS(43), 2,
      sym_lt,
      sym_gt,
    ACTIONS(41), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [578] = 2,
    ACTIONS(47), 2,
      sym_lt,
      sym_gt,
    ACTIONS(45), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [603] = 3,
    ACTIONS(51), 2,
      sym_lt,
      sym_gt,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(49), 15,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [630] = 6,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
  [663] = 4,
    ACTIONS(51), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(49), 13,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [692] = 5,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(51), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(49), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [723] = 2,
    ACTIONS(51), 2,
      sym_lt,
      sym_gt,
    ACTIONS(49), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [748] = 2,
    ACTIONS(65), 2,
      sym_lt,
      sym_gt,
    ACTIONS(63), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [773] = 2,
    ACTIONS(69), 2,
      sym_lt,
      sym_gt,
    ACTIONS(67), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [798] = 2,
    ACTIONS(73), 2,
      sym_lt,
      sym_gt,
    ACTIONS(71), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [823] = 2,
    ACTIONS(77), 2,
      sym_lt,
      sym_gt,
    ACTIONS(75), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [848] = 8,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(81), 1,
      sym_ternary_question,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(83), 2,
      sym_and,
      sym_or,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(79), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_colon,
    ACTIONS(59), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [885] = 3,
    ACTIONS(35), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(33), 14,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [910] = 3,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    ACTIONS(35), 2,
      sym_lt,
      sym_gt,
    ACTIONS(33), 14,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [934] = 8,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(81), 1,
      sym_ternary_question,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(83), 2,
      sym_and,
      sym_or,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [968] = 8,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(81), 1,
      sym_ternary_question,
    ACTIONS(91), 1,
      sym_ternary_colon,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(83), 2,
      sym_and,
      sym_or,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [1002] = 7,
    ACTIONS(57), 1,
      sym_string_concat,
    ACTIONS(81), 1,
      sym_ternary_question,
    ACTIONS(55), 2,
      sym_plus,
      sym_minus,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(83), 2,
      sym_and,
      sym_or,
    ACTIONS(53), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [1033] = 4,
    STATE(17), 1,
      sym_boolean_literal,
    STATE(28), 1,
      sym_literal,
    ACTIONS(93), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
  [1049] = 2,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    ACTIONS(97), 1,
      anon_sym_COMMA,
  [1056] = 1,
    ACTIONS(99), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1061] = 1,
    ACTIONS(101), 1,
      sym_identifier,
  [1065] = 1,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 37,
  [SMALL_STATE(5)] = 65,
  [SMALL_STATE(6)] = 109,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 191,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 273,
  [SMALL_STATE(11)] = 314,
  [SMALL_STATE(12)] = 355,
  [SMALL_STATE(13)] = 396,
  [SMALL_STATE(14)] = 437,
  [SMALL_STATE(15)] = 478,
  [SMALL_STATE(16)] = 503,
  [SMALL_STATE(17)] = 528,
  [SMALL_STATE(18)] = 553,
  [SMALL_STATE(19)] = 578,
  [SMALL_STATE(20)] = 603,
  [SMALL_STATE(21)] = 630,
  [SMALL_STATE(22)] = 663,
  [SMALL_STATE(23)] = 692,
  [SMALL_STATE(24)] = 723,
  [SMALL_STATE(25)] = 748,
  [SMALL_STATE(26)] = 773,
  [SMALL_STATE(27)] = 798,
  [SMALL_STATE(28)] = 823,
  [SMALL_STATE(29)] = 848,
  [SMALL_STATE(30)] = 885,
  [SMALL_STATE(31)] = 910,
  [SMALL_STATE(32)] = 934,
  [SMALL_STATE(33)] = 968,
  [SMALL_STATE(34)] = 1002,
  [SMALL_STATE(35)] = 1033,
  [SMALL_STATE(36)] = 1049,
  [SMALL_STATE(37)] = 1056,
  [SMALL_STATE(38)] = 1061,
  [SMALL_STATE(39)] = 1065,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access_expr, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access_expr, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expr, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mel, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [103] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
