/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  sym_number_literal = 6,
  sym_string_literal = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_regex_literal = 10,
  sym_ipv4_literal = 11,
  sym_ipv6_literal = 12,
  sym_plus = 13,
  sym_minus = 14,
  sym_bang = 15,
  sym_ternary_question = 16,
  sym_ternary_colon = 17,
  sym_and = 18,
  sym_or = 19,
  sym_string_concat = 20,
  sym_member_access = 21,
  sym_eq = 22,
  sym_ne = 23,
  sym_regex_eq = 24,
  sym_lt = 25,
  sym_lte = 26,
  sym_gt = 27,
  sym_gte = 28,
  sym_mul = 29,
  sym_div = 30,
  sym_modulo = 31,
  sym_ipmatch = 32,
  sym_mel = 33,
  sym_argument_list = 34,
  sym__arguments = 35,
  sym_argument = 36,
  sym_expr = 37,
  sym__hidden_expr = 38,
  sym__grouped_expr = 39,
  sym__simple_expr = 40,
  sym_assignment_expr = 41,
  sym_function_call_expr = 42,
  sym_binary_expr = 43,
  sym_prefix_expr = 44,
  sym__variable = 45,
  sym_member_access_expr = 46,
  sym_ternary_expr = 47,
  sym__literal_expr = 48,
  sym_literal = 49,
  sym_boolean_literal = 50,
  sym_ip_literal = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_regex_literal] = "regex_literal",
  [sym_ipv4_literal] = "ipv4_literal",
  [sym_ipv6_literal] = "ipv6_literal",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_bang] = "bang",
  [sym_ternary_question] = "ternary_question",
  [sym_ternary_colon] = "ternary_colon",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_string_concat] = "string_concat",
  [sym_member_access] = "member_access",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_regex_eq] = "regex_eq",
  [sym_lt] = "lt",
  [sym_lte] = "lte",
  [sym_gt] = "gt",
  [sym_gte] = "gte",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_modulo] = "modulo",
  [sym_ipmatch] = "ipmatch",
  [sym_mel] = "mel",
  [sym_argument_list] = "argument_list",
  [sym__arguments] = "_arguments",
  [sym_argument] = "argument",
  [sym_expr] = "expr",
  [sym__hidden_expr] = "_hidden_expr",
  [sym__grouped_expr] = "_grouped_expr",
  [sym__simple_expr] = "_simple_expr",
  [sym_assignment_expr] = "assignment_expr",
  [sym_function_call_expr] = "function_call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_prefix_expr] = "prefix_expr",
  [sym__variable] = "_variable",
  [sym_member_access_expr] = "member_access_expr",
  [sym_ternary_expr] = "ternary_expr",
  [sym__literal_expr] = "_literal_expr",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_ip_literal] = "ip_literal",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_regex_literal] = sym_regex_literal,
  [sym_ipv4_literal] = sym_ipv4_literal,
  [sym_ipv6_literal] = sym_ipv6_literal,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_bang] = sym_bang,
  [sym_ternary_question] = sym_ternary_question,
  [sym_ternary_colon] = sym_ternary_colon,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_string_concat] = sym_string_concat,
  [sym_member_access] = sym_member_access,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_regex_eq] = sym_regex_eq,
  [sym_lt] = sym_lt,
  [sym_lte] = sym_lte,
  [sym_gt] = sym_gt,
  [sym_gte] = sym_gte,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_modulo] = sym_modulo,
  [sym_ipmatch] = sym_ipmatch,
  [sym_mel] = sym_mel,
  [sym_argument_list] = sym_argument_list,
  [sym__arguments] = sym__arguments,
  [sym_argument] = sym_argument,
  [sym_expr] = sym_expr,
  [sym__hidden_expr] = sym__hidden_expr,
  [sym__grouped_expr] = sym__grouped_expr,
  [sym__simple_expr] = sym__simple_expr,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_function_call_expr] = sym_function_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_prefix_expr] = sym_prefix_expr,
  [sym__variable] = sym__variable,
  [sym_member_access_expr] = sym_member_access_expr,
  [sym_ternary_expr] = sym_ternary_expr,
  [sym__literal_expr] = sym__literal_expr,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_ip_literal] = sym_ip_literal,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_regex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_ipv4_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_ipv6_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_question] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_string_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_ipmatch] = {
    .visible = true,
    .named = true,
  },
  [sym_mel] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__hidden_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__grouped_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__variable] = {
    .visible = false,
    .named = true,
  },
  [sym_member_access_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__literal_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_ip_literal] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(103);
      ADVANCE_MAP(
        '!', 156,
        '"', 2,
        '%', 172,
        '(', 104,
        ')', 105,
        '*', 170,
        '+', 153,
        ',', 106,
        '-', 154,
        '.', 161,
        '/', 171,
        ':', 158,
        '<', 166,
        '=', 107,
        '>', 168,
        '?', 157,
        '^', 162,
        'a', 33,
        'f', 23,
        'i', 34,
        'o', 35,
        't', 36,
        '~', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'e')) ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(155);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(104);
      if (lookahead == ')') ADVANCE(105);
      if (lookahead == 'f') ADVANCE(109);
      if (lookahead == 't') ADVANCE(113);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'e')) ADVANCE(118);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(125);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(125);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(130);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(130);
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '#' ||
          lookahead == '$' ||
          ('(' <= lookahead && lookahead <= '+') ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '?' ||
          ('A' <= lookahead && lookahead <= '^') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(101);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(77);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(81);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(85);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(89);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(93);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(97);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 21:
      if (lookahead == '=') ADVANCE(164);
      END_STATE();
    case 22:
      if (lookahead == '=') ADVANCE(165);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(159);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 29:
      if (lookahead == 'h') ADVANCE(173);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'r') ADVANCE(160);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 40:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(98);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(100);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(96);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(96);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(100);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(98);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(92);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(152);
      END_STATE();
    case 73:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 74:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 84:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 85:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(84);
      END_STATE();
    case 86:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 87:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 88:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 89:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 90:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 91:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      END_STATE();
    case 92:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      END_STATE();
    case 93:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(92);
      END_STATE();
    case 94:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 95:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      END_STATE();
    case 96:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(95);
      END_STATE();
    case 97:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(96);
      END_STATE();
    case 98:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 99:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(98);
      END_STATE();
    case 100:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(99);
      END_STATE();
    case 101:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(100);
      END_STATE();
    case 102:
      if (eof) ADVANCE(103);
      ADVANCE_MAP(
        '!', 21,
        '%', 172,
        '(', 104,
        ')', 105,
        '*', 170,
        '+', 153,
        ',', 106,
        '-', 154,
        '.', 161,
        '/', 171,
        ':', 158,
        '<', 166,
        '=', 107,
        '>', 168,
        '?', 157,
        '^', 162,
        'a', 32,
        'i', 34,
        'o', 35,
        '~', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(163);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(101);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(117);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(116);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(115);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(111);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(108);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(116);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(117);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == ':') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(119);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_regex_literal);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (lookahead == ':') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(151);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(95);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(94);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_ipv4_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_ipv6_literal);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_bang);
      if (lookahead == '=') ADVANCE(164);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_ternary_question);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_ternary_colon);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_string_concat);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_member_access);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_regex_eq);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(167);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(169);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_modulo);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_ipmatch);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 102},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 102},
  [15] = {.lex_state = 102},
  [16] = {.lex_state = 102},
  [17] = {.lex_state = 102},
  [18] = {.lex_state = 102},
  [19] = {.lex_state = 102},
  [20] = {.lex_state = 102},
  [21] = {.lex_state = 102},
  [22] = {.lex_state = 102},
  [23] = {.lex_state = 102},
  [24] = {.lex_state = 102},
  [25] = {.lex_state = 102},
  [26] = {.lex_state = 102},
  [27] = {.lex_state = 102},
  [28] = {.lex_state = 102},
  [29] = {.lex_state = 102},
  [30] = {.lex_state = 102},
  [31] = {.lex_state = 102},
  [32] = {.lex_state = 102},
  [33] = {.lex_state = 102},
  [34] = {.lex_state = 102},
  [35] = {.lex_state = 102},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 40},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_regex_literal] = ACTIONS(1),
    [sym_ipv4_literal] = ACTIONS(1),
    [sym_ipv6_literal] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_ternary_question] = ACTIONS(1),
    [sym_ternary_colon] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_string_concat] = ACTIONS(1),
    [sym_member_access] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_regex_eq] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_modulo] = ACTIONS(1),
    [sym_ipmatch] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_mel] = STATE(40),
    [sym_expr] = STATE(34),
    [sym__hidden_expr] = STATE(29),
    [sym__grouped_expr] = STATE(29),
    [sym__simple_expr] = STATE(29),
    [sym_assignment_expr] = STATE(29),
    [sym_function_call_expr] = STATE(29),
    [sym_binary_expr] = STATE(29),
    [sym_prefix_expr] = STATE(29),
    [sym__variable] = STATE(5),
    [sym_member_access_expr] = STATE(5),
    [sym_ternary_expr] = STATE(29),
    [sym__literal_expr] = STATE(29),
    [sym_literal] = STATE(29),
    [sym_boolean_literal] = STATE(26),
    [sym_ip_literal] = STATE(26),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_regex_literal] = ACTIONS(9),
    [sym_ipv4_literal] = ACTIONS(13),
    [sym_ipv6_literal] = ACTIONS(15),
    [sym_bang] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__arguments] = STATE(38),
    [sym_argument] = STATE(38),
    [sym_expr] = STATE(35),
    [sym__hidden_expr] = STATE(31),
    [sym__grouped_expr] = STATE(31),
    [sym__simple_expr] = STATE(31),
    [sym_assignment_expr] = STATE(31),
    [sym_function_call_expr] = STATE(31),
    [sym_binary_expr] = STATE(31),
    [sym_prefix_expr] = STATE(31),
    [sym__variable] = STATE(5),
    [sym_member_access_expr] = STATE(5),
    [sym_ternary_expr] = STATE(31),
    [sym__literal_expr] = STATE(31),
    [sym_literal] = STATE(31),
    [sym_boolean_literal] = STATE(26),
    [sym_ip_literal] = STATE(26),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(19),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_regex_literal] = ACTIONS(9),
    [sym_ipv4_literal] = ACTIONS(13),
    [sym_ipv6_literal] = ACTIONS(15),
    [sym_bang] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(35), 1,
      sym_expr,
    STATE(37), 1,
      sym_argument,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(31), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [53] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(18), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [103] = 6,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(27), 1,
      sym_member_access,
    STATE(20), 1,
      sym_argument_list,
    ACTIONS(29), 2,
      sym_lt,
      sym_gt,
    ACTIONS(21), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [141] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(21), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [191] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(33), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [241] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(22), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [291] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(23), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [341] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(24), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [391] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(25), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [441] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(35), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(32), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [491] = 12,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    ACTIONS(17), 1,
      sym_bang,
    STATE(28), 1,
      sym_expr,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__variable,
      sym_member_access_expr,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [541] = 2,
    ACTIONS(33), 3,
      anon_sym_EQ,
      sym_lt,
      sym_gt,
    ACTIONS(31), 21,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_member_access,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [570] = 2,
    ACTIONS(37), 2,
      sym_lt,
      sym_gt,
    ACTIONS(35), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [596] = 2,
    ACTIONS(41), 2,
      sym_lt,
      sym_gt,
    ACTIONS(39), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [622] = 2,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [648] = 2,
    ACTIONS(49), 2,
      sym_lt,
      sym_gt,
    ACTIONS(47), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [674] = 2,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(51), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [700] = 2,
    ACTIONS(57), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [726] = 3,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [754] = 6,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(69), 6,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
  [788] = 4,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 14,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [818] = 5,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(59), 13,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [850] = 2,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(59), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [876] = 2,
    ACTIONS(75), 2,
      sym_lt,
      sym_gt,
    ACTIONS(73), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [902] = 2,
    ACTIONS(79), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [928] = 8,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(83), 1,
      sym_ternary_question,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 2,
      sym_and,
      sym_or,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_colon,
    ACTIONS(69), 6,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [966] = 2,
    ACTIONS(89), 2,
      sym_lt,
      sym_gt,
    ACTIONS(87), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [992] = 2,
    ACTIONS(93), 2,
      sym_lt,
      sym_gt,
    ACTIONS(91), 19,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [1018] = 3,
    ACTIONS(89), 2,
      sym_lt,
      sym_gt,
    ACTIONS(95), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(87), 15,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [1044] = 3,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(89), 2,
      sym_lt,
      sym_gt,
    ACTIONS(87), 15,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
      sym_ipmatch,
  [1069] = 8,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(83), 1,
      sym_ternary_question,
    ACTIONS(99), 1,
      sym_ternary_colon,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 2,
      sym_and,
      sym_or,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(69), 6,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [1104] = 8,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(83), 1,
      sym_ternary_question,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 2,
      sym_and,
      sym_or,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(69), 6,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [1139] = 7,
    ACTIONS(67), 1,
      sym_string_concat,
    ACTIONS(83), 1,
      sym_ternary_question,
    ACTIONS(65), 2,
      sym_plus,
      sym_minus,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 2,
      sym_and,
      sym_or,
    ACTIONS(63), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(69), 6,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_ipmatch,
  [1171] = 7,
    ACTIONS(7), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_ipv4_literal,
    ACTIONS(15), 1,
      sym_ipv6_literal,
    STATE(27), 1,
      sym_literal,
    ACTIONS(9), 2,
      sym_string_literal,
      sym_regex_literal,
    ACTIONS(103), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym_boolean_literal,
      sym_ip_literal,
  [1196] = 1,
    ACTIONS(105), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1201] = 2,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 1,
      anon_sym_COMMA,
  [1208] = 1,
    ACTIONS(111), 1,
      sym_identifier,
  [1212] = 1,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 53,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 141,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 241,
  [SMALL_STATE(9)] = 291,
  [SMALL_STATE(10)] = 341,
  [SMALL_STATE(11)] = 391,
  [SMALL_STATE(12)] = 441,
  [SMALL_STATE(13)] = 491,
  [SMALL_STATE(14)] = 541,
  [SMALL_STATE(15)] = 570,
  [SMALL_STATE(16)] = 596,
  [SMALL_STATE(17)] = 622,
  [SMALL_STATE(18)] = 648,
  [SMALL_STATE(19)] = 674,
  [SMALL_STATE(20)] = 700,
  [SMALL_STATE(21)] = 726,
  [SMALL_STATE(22)] = 754,
  [SMALL_STATE(23)] = 788,
  [SMALL_STATE(24)] = 818,
  [SMALL_STATE(25)] = 850,
  [SMALL_STATE(26)] = 876,
  [SMALL_STATE(27)] = 902,
  [SMALL_STATE(28)] = 928,
  [SMALL_STATE(29)] = 966,
  [SMALL_STATE(30)] = 992,
  [SMALL_STATE(31)] = 1018,
  [SMALL_STATE(32)] = 1044,
  [SMALL_STATE(33)] = 1069,
  [SMALL_STATE(34)] = 1104,
  [SMALL_STATE(35)] = 1139,
  [SMALL_STATE(36)] = 1171,
  [SMALL_STATE(37)] = 1196,
  [SMALL_STATE(38)] = 1201,
  [SMALL_STATE(39)] = 1208,
  [SMALL_STATE(40)] = 1212,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access_expr, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access_expr, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ip_literal, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ip_literal, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expr, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mel, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
