/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  sym_number_literal = 6,
  sym_string_literal = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_regex_literal = 10,
  sym_plus = 11,
  sym_minus = 12,
  sym_bang = 13,
  sym_ternary_question = 14,
  sym_ternary_colon = 15,
  sym_and = 16,
  sym_or = 17,
  sym_string_concat = 18,
  sym_eq = 19,
  sym_ne = 20,
  sym_regex_eq = 21,
  sym_lt = 22,
  sym_lte = 23,
  sym_gt = 24,
  sym_gte = 25,
  sym_mul = 26,
  sym_div = 27,
  sym_modulo = 28,
  sym_mel = 29,
  sym_argument_list = 30,
  sym__arguments = 31,
  sym_argument = 32,
  sym_expr = 33,
  sym__hidden_expr = 34,
  sym__grouped_expr = 35,
  sym__simple_expr = 36,
  sym_assignment_expr = 37,
  sym_function_call_expr = 38,
  sym_binary_expr = 39,
  sym_prefix_expr = 40,
  sym_ternary_expr = 41,
  sym__literal_expr = 42,
  sym_literal = 43,
  sym_boolean_literal = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_regex_literal] = "regex_literal",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_bang] = "bang",
  [sym_ternary_question] = "ternary_question",
  [sym_ternary_colon] = "ternary_colon",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_string_concat] = "string_concat",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_regex_eq] = "regex_eq",
  [sym_lt] = "lt",
  [sym_lte] = "lte",
  [sym_gt] = "gt",
  [sym_gte] = "gte",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_modulo] = "modulo",
  [sym_mel] = "mel",
  [sym_argument_list] = "argument_list",
  [sym__arguments] = "_arguments",
  [sym_argument] = "argument",
  [sym_expr] = "expr",
  [sym__hidden_expr] = "_hidden_expr",
  [sym__grouped_expr] = "_grouped_expr",
  [sym__simple_expr] = "_simple_expr",
  [sym_assignment_expr] = "assignment_expr",
  [sym_function_call_expr] = "function_call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_prefix_expr] = "prefix_expr",
  [sym_ternary_expr] = "ternary_expr",
  [sym__literal_expr] = "_literal_expr",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_regex_literal] = sym_regex_literal,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_bang] = sym_bang,
  [sym_ternary_question] = sym_ternary_question,
  [sym_ternary_colon] = sym_ternary_colon,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_string_concat] = sym_string_concat,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_regex_eq] = sym_regex_eq,
  [sym_lt] = sym_lt,
  [sym_lte] = sym_lte,
  [sym_gt] = sym_gt,
  [sym_gte] = sym_gte,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_modulo] = sym_modulo,
  [sym_mel] = sym_mel,
  [sym_argument_list] = sym_argument_list,
  [sym__arguments] = sym__arguments,
  [sym_argument] = sym_argument,
  [sym_expr] = sym_expr,
  [sym__hidden_expr] = sym__hidden_expr,
  [sym__grouped_expr] = sym__grouped_expr,
  [sym__simple_expr] = sym__simple_expr,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_function_call_expr] = sym_function_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_prefix_expr] = sym_prefix_expr,
  [sym_ternary_expr] = sym_ternary_expr,
  [sym__literal_expr] = sym__literal_expr,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_regex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_question] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_colon] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_string_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_mel] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__hidden_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__grouped_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__literal_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 43,
        '"', 2,
        '%', 58,
        '(', 21,
        ')', 22,
        '*', 56,
        '+', 40,
        ',', 23,
        '-', 41,
        '.', 48,
        '/', 57,
        ':', 45,
        '<', 52,
        '=', 24,
        '>', 54,
        '?', 44,
        'a', 14,
        'f', 9,
        'o', 15,
        't', 16,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(42);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 't') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 7,
        '%', 58,
        '(', 21,
        ')', 22,
        '*', 56,
        '+', 40,
        ',', 23,
        '-', 41,
        '.', 48,
        '/', 57,
        ':', 45,
        '<', 52,
        '=', 24,
        '>', 54,
        '?', 44,
        'a', 14,
        'o', 15,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_regex_literal);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_bang);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_ternary_question);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ternary_colon);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_string_concat);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_regex_eq);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_modulo);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 19},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 19},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 19},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 19},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 19},
  [26] = {.lex_state = 19},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 19},
  [29] = {.lex_state = 19},
  [30] = {.lex_state = 19},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 19},
  [33] = {.lex_state = 19},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_regex_literal] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_ternary_question] = ACTIONS(1),
    [sym_ternary_colon] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_string_concat] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_regex_eq] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_modulo] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_mel] = STATE(37),
    [sym_expr] = STATE(31),
    [sym__hidden_expr] = STATE(9),
    [sym__grouped_expr] = STATE(9),
    [sym__simple_expr] = STATE(9),
    [sym_assignment_expr] = STATE(9),
    [sym_function_call_expr] = STATE(9),
    [sym_binary_expr] = STATE(9),
    [sym_prefix_expr] = STATE(9),
    [sym_ternary_expr] = STATE(9),
    [sym__literal_expr] = STATE(9),
    [sym_literal] = STATE(9),
    [sym_boolean_literal] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_regex_literal] = ACTIONS(7),
    [sym_bang] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_argument_list] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(17),
    [sym_plus] = ACTIONS(13),
    [sym_minus] = ACTIONS(13),
    [sym_ternary_question] = ACTIONS(13),
    [sym_ternary_colon] = ACTIONS(13),
    [sym_and] = ACTIONS(13),
    [sym_or] = ACTIONS(13),
    [sym_string_concat] = ACTIONS(13),
    [sym_eq] = ACTIONS(13),
    [sym_ne] = ACTIONS(13),
    [sym_regex_eq] = ACTIONS(13),
    [sym_lt] = ACTIONS(19),
    [sym_lte] = ACTIONS(13),
    [sym_gt] = ACTIONS(19),
    [sym_gte] = ACTIONS(13),
    [sym_mul] = ACTIONS(13),
    [sym_div] = ACTIONS(13),
    [sym_modulo] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__arguments] = STATE(35),
    [sym_argument] = STATE(35),
    [sym_expr] = STATE(33),
    [sym__hidden_expr] = STATE(29),
    [sym__grouped_expr] = STATE(29),
    [sym__simple_expr] = STATE(29),
    [sym_assignment_expr] = STATE(29),
    [sym_function_call_expr] = STATE(29),
    [sym_binary_expr] = STATE(29),
    [sym_prefix_expr] = STATE(29),
    [sym_ternary_expr] = STATE(29),
    [sym__literal_expr] = STATE(29),
    [sym_literal] = STATE(29),
    [sym_boolean_literal] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_regex_literal] = ACTIONS(7),
    [sym_bang] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(33), 1,
      sym_expr,
    STATE(36), 1,
      sym_argument,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(29), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [40] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(22), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [77] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(8), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [114] = 2,
    ACTIONS(25), 2,
      sym_lt,
      sym_gt,
    ACTIONS(23), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [139] = 2,
    ACTIONS(29), 2,
      sym_lt,
      sym_gt,
    ACTIONS(27), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [164] = 2,
    ACTIONS(33), 2,
      sym_lt,
      sym_gt,
    ACTIONS(31), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [189] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(33), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(30), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [226] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(32), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [263] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(20), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [300] = 2,
    ACTIONS(37), 2,
      sym_lt,
      sym_gt,
    ACTIONS(35), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [325] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(23), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [362] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(19), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [399] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(24), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [436] = 2,
    ACTIONS(41), 2,
      sym_lt,
      sym_gt,
    ACTIONS(39), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [461] = 2,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [486] = 5,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(47), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [517] = 6,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(57), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
  [550] = 2,
    ACTIONS(63), 2,
      sym_lt,
      sym_gt,
    ACTIONS(61), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [575] = 3,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(47), 15,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [602] = 4,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(47), 13,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [631] = 2,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(47), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [656] = 2,
    ACTIONS(67), 2,
      sym_lt,
      sym_gt,
    ACTIONS(65), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [681] = 2,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(69), 18,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_ternary_colon,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [706] = 8,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(28), 1,
      sym_expr,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(9), 10,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_ternary_expr,
      sym__literal_expr,
      sym_literal,
  [743] = 8,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(75), 1,
      sym_ternary_question,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 2,
      sym_and,
      sym_or,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_ternary_colon,
    ACTIONS(57), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [780] = 3,
    ACTIONS(33), 2,
      sym_lt,
      sym_gt,
    ACTIONS(79), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(31), 14,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [805] = 3,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    ACTIONS(33), 2,
      sym_lt,
      sym_gt,
    ACTIONS(31), 14,
      sym_plus,
      sym_minus,
      sym_ternary_question,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [829] = 8,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(75), 1,
      sym_ternary_question,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 2,
      sym_and,
      sym_or,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(57), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [863] = 8,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(75), 1,
      sym_ternary_question,
    ACTIONS(85), 1,
      sym_ternary_colon,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 2,
      sym_and,
      sym_or,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(57), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [897] = 7,
    ACTIONS(51), 1,
      sym_string_concat,
    ACTIONS(75), 1,
      sym_ternary_question,
    ACTIONS(49), 2,
      sym_plus,
      sym_minus,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 2,
      sym_and,
      sym_or,
    ACTIONS(55), 3,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(57), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [928] = 4,
    STATE(7), 1,
      sym_boolean_literal,
    STATE(21), 1,
      sym_literal,
    ACTIONS(87), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
  [944] = 2,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    ACTIONS(91), 1,
      anon_sym_COMMA,
  [951] = 1,
    ACTIONS(93), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [956] = 1,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 77,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 139,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 189,
  [SMALL_STATE(11)] = 226,
  [SMALL_STATE(12)] = 263,
  [SMALL_STATE(13)] = 300,
  [SMALL_STATE(14)] = 325,
  [SMALL_STATE(15)] = 362,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 436,
  [SMALL_STATE(18)] = 461,
  [SMALL_STATE(19)] = 486,
  [SMALL_STATE(20)] = 517,
  [SMALL_STATE(21)] = 550,
  [SMALL_STATE(22)] = 575,
  [SMALL_STATE(23)] = 602,
  [SMALL_STATE(24)] = 631,
  [SMALL_STATE(25)] = 656,
  [SMALL_STATE(26)] = 681,
  [SMALL_STATE(27)] = 706,
  [SMALL_STATE(28)] = 743,
  [SMALL_STATE(29)] = 780,
  [SMALL_STATE(30)] = 805,
  [SMALL_STATE(31)] = 829,
  [SMALL_STATE(32)] = 863,
  [SMALL_STATE(33)] = 897,
  [SMALL_STATE(34)] = 928,
  [SMALL_STATE(35)] = 944,
  [SMALL_STATE(36)] = 951,
  [SMALL_STATE(37)] = 956,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expr, 5, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mel, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
