/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_COMMA = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_EQ = 6,
  sym_identifier = 7,
  sym_number_literal = 8,
  sym_string_literal = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_plus = 12,
  sym_minus = 13,
  sym_bang = 14,
  sym_uneg = 15,
  sym_and = 16,
  sym_or = 17,
  sym_string_concat = 18,
  sym_eq = 19,
  sym_lt = 20,
  sym_lte = 21,
  sym_gt = 22,
  sym_gte = 23,
  sym_mul = 24,
  sym_div = 25,
  sym_mel = 26,
  sym_list = 27,
  sym_expr_list = 28,
  sym_argument_list = 29,
  sym_arguments = 30,
  sym_expr = 31,
  sym_grouped_expr = 32,
  sym_simple_expr = 33,
  sym_assignment_expr = 34,
  sym_function_call_expr = 35,
  sym_binary_expr = 36,
  sym_prefix_expr = 37,
  sym_literal_expr = 38,
  sym_literal = 39,
  sym_boolean_literal = 40,
  sym_binary_infix_operator = 41,
  sym_logic_operator = 42,
  sym_comparison_operator = 43,
  sym_math_operator = 44,
  sym_prefix_operator = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_bang] = "bang",
  [sym_uneg] = "uneg",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_string_concat] = "string_concat",
  [sym_eq] = "eq",
  [sym_lt] = "lt",
  [sym_lte] = "lte",
  [sym_gt] = "gt",
  [sym_gte] = "gte",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_mel] = "mel",
  [sym_list] = "list",
  [sym_expr_list] = "expr_list",
  [sym_argument_list] = "argument_list",
  [sym_arguments] = "arguments",
  [sym_expr] = "expr",
  [sym_grouped_expr] = "grouped_expr",
  [sym_simple_expr] = "simple_expr",
  [sym_assignment_expr] = "assignment_expr",
  [sym_function_call_expr] = "function_call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_prefix_expr] = "prefix_expr",
  [sym_literal_expr] = "literal_expr",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_binary_infix_operator] = "binary_infix_operator",
  [sym_logic_operator] = "logic_operator",
  [sym_comparison_operator] = "comparison_operator",
  [sym_math_operator] = "math_operator",
  [sym_prefix_operator] = "prefix_operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_bang] = sym_bang,
  [sym_uneg] = sym_uneg,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_string_concat] = sym_string_concat,
  [sym_eq] = sym_eq,
  [sym_lt] = sym_lt,
  [sym_lte] = sym_lte,
  [sym_gt] = sym_gt,
  [sym_gte] = sym_gte,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_mel] = sym_mel,
  [sym_list] = sym_list,
  [sym_expr_list] = sym_expr_list,
  [sym_argument_list] = sym_argument_list,
  [sym_arguments] = sym_arguments,
  [sym_expr] = sym_expr,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_simple_expr] = sym_simple_expr,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_function_call_expr] = sym_function_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_prefix_expr] = sym_prefix_expr,
  [sym_literal_expr] = sym_literal_expr,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_binary_infix_operator] = sym_binary_infix_operator,
  [sym_logic_operator] = sym_logic_operator,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_math_operator] = sym_math_operator,
  [sym_prefix_operator] = sym_prefix_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_uneg] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_string_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_mel] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_infix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_math_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_operator] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 36,
        '"', 2,
        '(', 17,
        ')', 18,
        '*', 46,
        '+', 34,
        ',', 16,
        '-', 35,
        '.', 40,
        '/', 47,
        '<', 42,
        '=', 19,
        '>', 44,
        '[', 14,
        ']', 15,
        'a', 8,
        'f', 3,
        'o', 9,
        't', 10,
        '~', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 36,
        '"', 2,
        '(', 17,
        ')', 18,
        '+', 34,
        '-', 35,
        '[', 14,
        ']', 15,
        'f', 20,
        't', 24,
        '~', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_uneg);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string_concat);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_uneg] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_string_concat] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_mel] = STATE(38),
    [sym_list] = STATE(39),
    [sym_expr] = STATE(17),
    [sym_grouped_expr] = STATE(20),
    [sym_simple_expr] = STATE(20),
    [sym_assignment_expr] = STATE(18),
    [sym_function_call_expr] = STATE(18),
    [sym_binary_expr] = STATE(18),
    [sym_prefix_expr] = STATE(18),
    [sym_literal_expr] = STATE(18),
    [sym_literal] = STATE(21),
    [sym_boolean_literal] = STATE(22),
    [sym_prefix_operator] = STATE(5),
    [anon_sym_LBRACK] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_number_literal] = ACTIONS(9),
    [sym_string_literal] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_plus] = ACTIONS(13),
    [sym_minus] = ACTIONS(13),
    [sym_bang] = ACTIONS(13),
    [sym_uneg] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(14), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    STATE(35), 1,
      sym_arguments,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [50] = 13,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(12), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    STATE(34), 1,
      sym_expr_list,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [100] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(16), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [144] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(10), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [188] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(13), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [232] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(9), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [276] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(5), 1,
      sym_prefix_operator,
    STATE(15), 1,
      sym_expr,
    STATE(21), 1,
      sym_literal,
    STATE(22), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_grouped_expr,
      sym_simple_expr,
    ACTIONS(13), 4,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
    STATE(18), 5,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym_literal_expr,
  [320] = 4,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(21), 2,
      sym_lt,
      sym_gt,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(19), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [349] = 4,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(25), 2,
      sym_lt,
      sym_gt,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(23), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [378] = 5,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_EQ,
    STATE(19), 1,
      sym_argument_list,
    ACTIONS(33), 2,
      sym_lt,
      sym_gt,
    ACTIONS(27), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [408] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(35), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [443] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(47), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [478] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(49), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [513] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(51), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [548] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [582] = 8,
    ACTIONS(41), 1,
      sym_string_concat,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_binary_infix_operator,
    ACTIONS(39), 2,
      sym_and,
      sym_or,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 3,
      sym_eq,
      sym_lte,
      sym_gte,
    STATE(30), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(37), 4,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
  [616] = 2,
    ACTIONS(33), 2,
      sym_lt,
      sym_gt,
    ACTIONS(27), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [637] = 2,
    ACTIONS(59), 2,
      sym_lt,
      sym_gt,
    ACTIONS(57), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [658] = 2,
    ACTIONS(63), 2,
      sym_lt,
      sym_gt,
    ACTIONS(61), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [679] = 2,
    ACTIONS(67), 2,
      sym_lt,
      sym_gt,
    ACTIONS(65), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [700] = 2,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [721] = 2,
    ACTIONS(75), 2,
      sym_lt,
      sym_gt,
    ACTIONS(73), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [742] = 2,
    ACTIONS(79), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [763] = 2,
    ACTIONS(83), 2,
      sym_lt,
      sym_gt,
    ACTIONS(81), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [784] = 2,
    ACTIONS(87), 2,
      sym_lt,
      sym_gt,
    ACTIONS(85), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [805] = 2,
    ACTIONS(91), 2,
      sym_lt,
      sym_gt,
    ACTIONS(89), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
  [826] = 2,
    ACTIONS(95), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(93), 7,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
  [841] = 2,
    ACTIONS(99), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 7,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
  [856] = 2,
    ACTIONS(103), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 7,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
  [871] = 2,
    ACTIONS(107), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(105), 7,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
  [886] = 2,
    ACTIONS(111), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(109), 7,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_plus,
      sym_minus,
      sym_bang,
      sym_uneg,
  [901] = 4,
    STATE(22), 1,
      sym_boolean_literal,
    STATE(24), 1,
      sym_literal,
    ACTIONS(9), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(113), 2,
      anon_sym_true,
      anon_sym_false,
  [916] = 2,
    ACTIONS(115), 1,
      anon_sym_RBRACK,
    ACTIONS(117), 1,
      anon_sym_COMMA,
  [923] = 2,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
  [930] = 1,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
  [934] = 1,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
  [938] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [942] = 1,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 188,
  [SMALL_STATE(7)] = 232,
  [SMALL_STATE(8)] = 276,
  [SMALL_STATE(9)] = 320,
  [SMALL_STATE(10)] = 349,
  [SMALL_STATE(11)] = 378,
  [SMALL_STATE(12)] = 408,
  [SMALL_STATE(13)] = 443,
  [SMALL_STATE(14)] = 478,
  [SMALL_STATE(15)] = 513,
  [SMALL_STATE(16)] = 548,
  [SMALL_STATE(17)] = 582,
  [SMALL_STATE(18)] = 616,
  [SMALL_STATE(19)] = 637,
  [SMALL_STATE(20)] = 658,
  [SMALL_STATE(21)] = 679,
  [SMALL_STATE(22)] = 700,
  [SMALL_STATE(23)] = 721,
  [SMALL_STATE(24)] = 742,
  [SMALL_STATE(25)] = 763,
  [SMALL_STATE(26)] = 784,
  [SMALL_STATE(27)] = 805,
  [SMALL_STATE(28)] = 826,
  [SMALL_STATE(29)] = 841,
  [SMALL_STATE(30)] = 856,
  [SMALL_STATE(31)] = 871,
  [SMALL_STATE(32)] = 886,
  [SMALL_STATE(33)] = 901,
  [SMALL_STATE(34)] = 916,
  [SMALL_STATE(35)] = 923,
  [SMALL_STATE(36)] = 930,
  [SMALL_STATE(37)] = 934,
  [SMALL_STATE(38)] = 938,
  [SMALL_STATE(39)] = 942,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_expr, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_expr, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_list, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_list, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mel, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_operator, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_operator, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_operator, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logic_operator, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_infix_operator, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_infix_operator, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_operator, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
