/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 31
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COMMA = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  sym_number_literal = 6,
  sym_string_literal = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_regex_literal = 10,
  sym_plus = 11,
  sym_minus = 12,
  sym_bang = 13,
  sym_and = 14,
  sym_or = 15,
  sym_string_concat = 16,
  sym_eq = 17,
  sym_ne = 18,
  sym_regex_eq = 19,
  sym_lt = 20,
  sym_lte = 21,
  sym_gt = 22,
  sym_gte = 23,
  sym_mul = 24,
  sym_div = 25,
  sym_modulo = 26,
  sym_mel = 27,
  sym_argument_list = 28,
  sym__arguments = 29,
  sym_argument = 30,
  sym_expr = 31,
  sym__hidden_expr = 32,
  sym__grouped_expr = 33,
  sym__simple_expr = 34,
  sym_assignment_expr = 35,
  sym_function_call_expr = 36,
  sym_binary_expr = 37,
  sym_prefix_expr = 38,
  sym__literal_expr = 39,
  sym_literal = 40,
  sym_boolean_literal = 41,
  sym_binary_infix_operator = 42,
  sym_logic_operator = 43,
  sym_comparison_operator = 44,
  sym_math_operator = 45,
  sym_prefix_operator = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_regex_literal] = "regex_literal",
  [sym_plus] = "plus",
  [sym_minus] = "minus",
  [sym_bang] = "bang",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_string_concat] = "string_concat",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_regex_eq] = "regex_eq",
  [sym_lt] = "lt",
  [sym_lte] = "lte",
  [sym_gt] = "gt",
  [sym_gte] = "gte",
  [sym_mul] = "mul",
  [sym_div] = "div",
  [sym_modulo] = "modulo",
  [sym_mel] = "mel",
  [sym_argument_list] = "argument_list",
  [sym__arguments] = "_arguments",
  [sym_argument] = "argument",
  [sym_expr] = "expr",
  [sym__hidden_expr] = "_hidden_expr",
  [sym__grouped_expr] = "_grouped_expr",
  [sym__simple_expr] = "_simple_expr",
  [sym_assignment_expr] = "assignment_expr",
  [sym_function_call_expr] = "function_call_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_prefix_expr] = "prefix_expr",
  [sym__literal_expr] = "_literal_expr",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_binary_infix_operator] = "binary_infix_operator",
  [sym_logic_operator] = "logic_operator",
  [sym_comparison_operator] = "comparison_operator",
  [sym_math_operator] = "math_operator",
  [sym_prefix_operator] = "prefix_operator",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_regex_literal] = sym_regex_literal,
  [sym_plus] = sym_plus,
  [sym_minus] = sym_minus,
  [sym_bang] = sym_bang,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_string_concat] = sym_string_concat,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_regex_eq] = sym_regex_eq,
  [sym_lt] = sym_lt,
  [sym_lte] = sym_lte,
  [sym_gt] = sym_gt,
  [sym_gte] = sym_gte,
  [sym_mul] = sym_mul,
  [sym_div] = sym_div,
  [sym_modulo] = sym_modulo,
  [sym_mel] = sym_mel,
  [sym_argument_list] = sym_argument_list,
  [sym__arguments] = sym__arguments,
  [sym_argument] = sym_argument,
  [sym_expr] = sym_expr,
  [sym__hidden_expr] = sym__hidden_expr,
  [sym__grouped_expr] = sym__grouped_expr,
  [sym__simple_expr] = sym__simple_expr,
  [sym_assignment_expr] = sym_assignment_expr,
  [sym_function_call_expr] = sym_function_call_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_prefix_expr] = sym_prefix_expr,
  [sym__literal_expr] = sym__literal_expr,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_binary_infix_operator] = sym_binary_infix_operator,
  [sym_logic_operator] = sym_logic_operator,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_math_operator] = sym_math_operator,
  [sym_prefix_operator] = sym_prefix_operator,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_regex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_plus] = {
    .visible = true,
    .named = true,
  },
  [sym_minus] = {
    .visible = true,
    .named = true,
  },
  [sym_bang] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_string_concat] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_regex_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_lte] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_gte] = {
    .visible = true,
    .named = true,
  },
  [sym_mul] = {
    .visible = true,
    .named = true,
  },
  [sym_div] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo] = {
    .visible = true,
    .named = true,
  },
  [sym_mel] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__hidden_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__grouped_expr] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__literal_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_infix_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_math_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix_operator] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 43,
        '"', 2,
        '%', 56,
        '(', 21,
        ')', 22,
        '*', 54,
        '+', 40,
        ',', 23,
        '-', 41,
        '.', 46,
        '/', 55,
        '<', 50,
        '=', 24,
        '>', 52,
        'a', 14,
        'f', 9,
        'o', 15,
        't', 16,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(42);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 't') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(39);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == 'i') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 7,
        '%', 56,
        '(', 21,
        ')', 22,
        '*', 54,
        '+', 40,
        ',', 23,
        '-', 41,
        '.', 46,
        '/', 55,
        '<', 50,
        '=', 24,
        '>', 52,
        'a', 14,
        'o', 15,
        '~', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_regex_literal);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_plus);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_minus);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_bang);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_bang);
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_string_concat);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_regex_eq);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_lte);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_gte);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_mul);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_div);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_modulo);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 19},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 19},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 19},
  [16] = {.lex_state = 19},
  [17] = {.lex_state = 19},
  [18] = {.lex_state = 19},
  [19] = {.lex_state = 19},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_regex_literal] = ACTIONS(1),
    [sym_plus] = ACTIONS(1),
    [sym_minus] = ACTIONS(1),
    [sym_bang] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
    [sym_string_concat] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_regex_eq] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_lte] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_gte] = ACTIONS(1),
    [sym_mul] = ACTIONS(1),
    [sym_div] = ACTIONS(1),
    [sym_modulo] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_mel] = STATE(30),
    [sym_expr] = STATE(8),
    [sym__hidden_expr] = STATE(13),
    [sym__grouped_expr] = STATE(13),
    [sym__simple_expr] = STATE(13),
    [sym_assignment_expr] = STATE(13),
    [sym_function_call_expr] = STATE(13),
    [sym_binary_expr] = STATE(13),
    [sym_prefix_expr] = STATE(13),
    [sym__literal_expr] = STATE(13),
    [sym_literal] = STATE(13),
    [sym_boolean_literal] = STATE(12),
    [sym_prefix_operator] = STATE(9),
    [anon_sym_LPAREN] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_number_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_true] = ACTIONS(9),
    [anon_sym_false] = ACTIONS(9),
    [sym_regex_literal] = ACTIONS(7),
    [sym_bang] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    ACTIONS(13), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_prefix_operator,
    STATE(11), 1,
      sym_expr,
    STATE(12), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 2,
      sym__arguments,
      sym_argument,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(20), 9,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym__literal_expr,
      sym_literal,
  [46] = 4,
    STATE(10), 1,
      sym_binary_infix_operator,
    ACTIONS(17), 2,
      sym_lt,
      sym_gt,
    STATE(26), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(15), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [77] = 4,
    STATE(10), 1,
      sym_binary_infix_operator,
    ACTIONS(21), 2,
      sym_lt,
      sym_gt,
    STATE(26), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(19), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [108] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      anon_sym_EQ,
    STATE(15), 1,
      sym_argument_list,
    ACTIONS(29), 2,
      sym_lt,
      sym_gt,
    ACTIONS(23), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [140] = 10,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(9), 1,
      sym_prefix_operator,
    STATE(11), 1,
      sym_expr,
    STATE(12), 1,
      sym_boolean_literal,
    STATE(29), 1,
      sym_argument,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(20), 9,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym__literal_expr,
      sym_literal,
  [182] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(9), 1,
      sym_prefix_operator,
    STATE(11), 1,
      sym_expr,
    STATE(12), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(21), 9,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym__literal_expr,
      sym_literal,
  [221] = 8,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_string_concat,
    STATE(10), 1,
      sym_binary_infix_operator,
    ACTIONS(35), 2,
      sym_and,
      sym_or,
    ACTIONS(41), 2,
      sym_lt,
      sym_gt,
    STATE(26), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(33), 5,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(39), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [258] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(4), 1,
      sym_expr,
    STATE(9), 1,
      sym_prefix_operator,
    STATE(12), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(13), 9,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym__literal_expr,
      sym_literal,
  [297] = 9,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(11), 1,
      sym_bang,
    STATE(3), 1,
      sym_expr,
    STATE(9), 1,
      sym_prefix_operator,
    STATE(12), 1,
      sym_boolean_literal,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
    STATE(13), 9,
      sym__hidden_expr,
      sym__grouped_expr,
      sym__simple_expr,
      sym_assignment_expr,
      sym_function_call_expr,
      sym_binary_expr,
      sym_prefix_expr,
      sym__literal_expr,
      sym_literal,
  [336] = 7,
    ACTIONS(37), 1,
      sym_string_concat,
    STATE(10), 1,
      sym_binary_infix_operator,
    ACTIONS(35), 2,
      sym_and,
      sym_or,
    ACTIONS(41), 2,
      sym_lt,
      sym_gt,
    STATE(26), 3,
      sym_logic_operator,
      sym_comparison_operator,
      sym_math_operator,
    ACTIONS(33), 5,
      sym_plus,
      sym_minus,
      sym_mul,
      sym_div,
      sym_modulo,
    ACTIONS(39), 5,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
  [370] = 2,
    ACTIONS(45), 2,
      sym_lt,
      sym_gt,
    ACTIONS(43), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [393] = 2,
    ACTIONS(49), 2,
      sym_lt,
      sym_gt,
    ACTIONS(47), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [416] = 2,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    ACTIONS(51), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [439] = 2,
    ACTIONS(57), 2,
      sym_lt,
      sym_gt,
    ACTIONS(55), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [462] = 2,
    ACTIONS(61), 2,
      sym_lt,
      sym_gt,
    ACTIONS(59), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [485] = 2,
    ACTIONS(65), 2,
      sym_lt,
      sym_gt,
    ACTIONS(63), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [508] = 2,
    ACTIONS(69), 2,
      sym_lt,
      sym_gt,
    ACTIONS(67), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [531] = 2,
    ACTIONS(73), 2,
      sym_lt,
      sym_gt,
    ACTIONS(71), 16,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [554] = 3,
    ACTIONS(49), 2,
      sym_lt,
      sym_gt,
    ACTIONS(75), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(47), 13,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [578] = 3,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(49), 2,
      sym_lt,
      sym_gt,
    ACTIONS(47), 13,
      sym_plus,
      sym_minus,
      sym_and,
      sym_or,
      sym_string_concat,
      sym_eq,
      sym_ne,
      sym_regex_eq,
      sym_lte,
      sym_gte,
      sym_mul,
      sym_div,
      sym_modulo,
  [601] = 2,
    ACTIONS(81), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(79), 5,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
      sym_bang,
  [614] = 2,
    ACTIONS(85), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(83), 5,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
      sym_bang,
  [627] = 2,
    ACTIONS(89), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(87), 5,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
      sym_bang,
  [640] = 2,
    ACTIONS(93), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 5,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
      sym_bang,
  [653] = 2,
    ACTIONS(97), 3,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(95), 5,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
      sym_bang,
  [666] = 4,
    STATE(12), 1,
      sym_boolean_literal,
    STATE(16), 1,
      sym_literal,
    ACTIONS(99), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 3,
      sym_number_literal,
      sym_string_literal,
      sym_regex_literal,
  [682] = 2,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 1,
      anon_sym_COMMA,
  [689] = 1,
    ACTIONS(105), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [694] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 182,
  [SMALL_STATE(8)] = 221,
  [SMALL_STATE(9)] = 258,
  [SMALL_STATE(10)] = 297,
  [SMALL_STATE(11)] = 336,
  [SMALL_STATE(12)] = 370,
  [SMALL_STATE(13)] = 393,
  [SMALL_STATE(14)] = 416,
  [SMALL_STATE(15)] = 439,
  [SMALL_STATE(16)] = 462,
  [SMALL_STATE(17)] = 485,
  [SMALL_STATE(18)] = 508,
  [SMALL_STATE(19)] = 531,
  [SMALL_STATE(20)] = 554,
  [SMALL_STATE(21)] = 578,
  [SMALL_STATE(22)] = 601,
  [SMALL_STATE(23)] = 614,
  [SMALL_STATE(24)] = 627,
  [SMALL_STATE(25)] = 640,
  [SMALL_STATE(26)] = 653,
  [SMALL_STATE(27)] = 666,
  [SMALL_STATE(28)] = 682,
  [SMALL_STATE(29)] = 689,
  [SMALL_STATE(30)] = 694,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_expr, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expr, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mel, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call_expr, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expr, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expr, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefix_operator, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logic_operator, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logic_operator, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_operator, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_operator, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison_operator, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison_operator, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_infix_operator, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_infix_operator, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mel(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mel",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
