on: [push, pull_request]

name: Continuous Integration

jobs:
  grammar-tests:
    name: Grammar Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - uses: tree-sitter/setup-action@v2
      # Because our tree-sitter code is in a subdirectory,
      # and working-directory does not apply to uses, we
      # are forced to specify calls to the CI ourselves.
      # See https://github.com/orgs/community/discussions/25742
      - run: tree-sitter generate
        working-directory: ./parser
      - run: tree-sitter test
        working-directory: ./parser
  library-tests:
    name: Library Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tree-sitter/setup-action@v2
      # Because our tree-sitter code is in a subdirectory,
      # and working-directory does not apply to uses, we
      # are forced to specify calls to the CI ourselves.
      # See https://github.com/orgs/community/discussions/25742
      - run: tree-sitter generate
        working-directory: ./parser
      - run: cargo build
      - run: cargo test
      - run: cargo test --manifest-path parser/Cargo.toml
  library-format-tests:
    name: Library Format Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: tree-sitter/setup-action@v2
      # Because our tree-sitter code is in a subdirectory,
      # and working-directory does not apply to uses, we
      # are forced to specify calls to the CI ourselves.
      # See https://github.com/orgs/community/discussions/25742
      - run: tree-sitter generate
        working-directory: ./parser
      - run: cargo build
      - run: cargo doc --no-deps
      - name: Delete lock file
        shell: sh
        run: rm -f target/doc/.lock
      - name: Fix file permissions
        shell: sh
        run: chmod -R a+rX target/doc
      - name: Generate index.html file
        run: |
            echo "<meta http-equiv=refresh content=0;url=brooks_lib/index.html>" > target/doc/index.html
      - name: List file permissions
        shell: sh
        run: ls -latr target/doc
      - name: Upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: target/doc
      - name: Deploy Docs
        uses: actions/deploy-pages@v4

